version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 108782086589.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t devops-team11 .
      - docker tag devops-team11:latest 108782086589.dkr.ecr.us-east-1.amazonaws.com/devops-team11:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 108782086589.dkr.ecr.us-east-1.amazonaws.com/devops-team11:latest
      - echo Writing Image Definitions file...
      - printf '[{"name":"Container-devops-team11","imageUri":"108782086589.dkr.ecr.us-east-1.amazonaws.com/devops-team11:latest"}]' > imagedefinitions.json
      - printf '{"ImageURI":"108782086589.dkr.ecr.us-east-1.amazonaws.com/devops-team11:latest"}' > imageDetail.json
      - cat imagedefinitions.json
artifacts:
  files:
    - '**/*'
    - imagedefinitions.json
    - imageDetail.json
  secondary-artifacts:
    DefinitionArtifact:
      files:
        - appspec.yaml
        - taskdef.json
    ImageArtifact:
      files:
        - imageDetail.json